// <auto-generated />
using System;
using Cn2x.Iryo.UlceraVenosa.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cn2x.Iryo.UlceraVenosa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250707155701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.AvaliacaoUlcera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_avaliacao");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<string>("Duracao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("duracao");

                    b.Property<Guid>("UlceraId")
                        .HasColumnType("uuid")
                        .HasColumnName("ulcera_id");

                    b.HasKey("Id")
                        .HasName("pk_avaliacoes_ulcera");

                    b.HasIndex("UlceraId")
                        .HasDatabaseName("ix_avaliacoes_ulcera_ulcera_id");

                    b.ToTable("avaliacoes_ulcera", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Exsudato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_exsudato_tipos");

                    b.ToTable("exsudatos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Seroso - Transparente ou levemente amarelo, aquoso, fluido. Indicação: Fase inflamatória leve ou cicatrização. Conduta: Monitorar, manter hidratação da ferida."
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Serossanguinolento - Rosa claro, diluído com sangue, levemente viscoso. Indicação: Trauma leve ou início de granulação. Conduta: Avaliar trauma, proteger bordas."
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Sanguinolento - Vermelho vivo, líquido a viscoso. Indicação: Sangramento ativo ou lesão capilar. Conduta: Estancar, avaliar necessidade de sutura."
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Hemorrágico - Vermelho escuro ou vivo, espesso, com coágulos. Indicação: Hemorragia arterial ou venosa local. Conduta: Urgência médica, hemostasia."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Purulento - Amarelo, esverdeado ou acastanhado, espesso, fétido. Indicação: Infecção bacteriana ativa. Conduta: Cultura, antibioticoterapia, limpeza."
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Fibrinoso - Esbranquiçado ou amarelado, gelatinoso, filamentoso. Indicação: Presença de fibrina, biofilme. Conduta: Desbridamento, controle da umidade."
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Catarral - Esbranquiçado e mucoide, viscoso. Indicação: Presente em áreas mucosas ou com inflamação leve. Conduta: Raro em úlceras venosas, observar."
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Necrótico - Marrom, cinza ou preto, espesso, seco ou úmido. Indicação: Presença de necrose tecidual. Conduta: Desbridamento enzimático ou cirúrgico."
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Putrilaginoso - Cinza-esverdeado, muito espesso, pegajoso, fétido. Indicação: Infecção crítica, tecido desvitalizado. Conduta: Ação rápida: desbridamento + antibiótico."
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Hiperexsudativo - Variável, muito abundante. Indicação: Descompensação venosa, linforreia, infecção. Conduta: Curativos superabsorventes, compressão."
                        });
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.ExsudatoDaAvaliacao", b =>
                {
                    b.Property<Guid>("AvaliacaoUlceraId")
                        .HasColumnType("uuid")
                        .HasColumnName("avaliacao_ulcera_id");

                    b.Property<Guid>("ExsudatoId")
                        .HasColumnType("uuid")
                        .HasColumnName("exsudato_id");

                    b.HasKey("AvaliacaoUlceraId", "ExsudatoId");

                    b.HasIndex("ExsudatoId")
                        .HasDatabaseName("ix_exsudatos_avaliacao_exsudato_id");

                    b.ToTable("exsudatos_avaliacao", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.ExsudatoDaUlcera", b =>
                {
                    b.Property<Guid>("UlceraId")
                        .HasColumnType("uuid")
                        .HasColumnName("ulcera_id");

                    b.Property<Guid>("ExsudatoId")
                        .HasColumnType("uuid")
                        .HasColumnName("exsudato_id");

                    b.HasKey("UlceraId", "ExsudatoId");

                    b.HasIndex("ExsudatoId")
                        .HasDatabaseName("ix_exsudatos_exsudato_id");

                    b.ToTable("exsudatos_da_ulcera", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.ImagemUlcera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caminho_arquivo");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataCaptura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_captura");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<bool>("EhImagemPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_imagem_principal");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_arquivo");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer")
                        .HasColumnName("ordem_exibicao");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<Guid>("UlceraId")
                        .HasColumnType("uuid")
                        .HasColumnName("ulcera_id");

                    b.Property<Guid>("UlceraId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_imagem_ulcera");

                    b.HasIndex("UlceraId")
                        .HasDatabaseName("ix_imagem_ulcera_ulcera_id");

                    b.HasIndex("UlceraId1");

                    b.ToTable("imagem_ulcera");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Medida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Comprimento")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("comprimento");

                    b.Property<decimal?>("Largura")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("largura");

                    b.Property<decimal?>("Profundidade")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("profundidade");

                    b.Property<Guid>("UlceraId")
                        .HasColumnType("uuid")
                        .HasColumnName("ulcera_id");

                    b.HasKey("Id")
                        .HasName("pk_medidas");

                    b.HasIndex("UlceraId")
                        .IsUnique()
                        .HasDatabaseName("ix_medidas_ulcera_id");

                    b.ToTable("medidas", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_pacientes");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.RegiaoAnatomica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<string>("Limites")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("limites");

                    b.Property<Guid>("SegmentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("segmento_id");

                    b.HasKey("Id")
                        .HasName("pk_regioes_anatomicas");

                    b.HasIndex("SegmentoId")
                        .HasDatabaseName("ix_regioes_anatomicas_segmento_id");

                    b.ToTable("regioes_anatomicas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CriadoEm = new DateTime(2025, 6, 28, 18, 30, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Limites = "Região maleolar - Ao redor do maléolo medial e lateral (tornozelo). Frequência: 10%",
                            SegmentoId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CriadoEm = new DateTime(2025, 6, 28, 18, 30, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Limites = "Terço inferior da perna - Entre a base do tornozelo e a metade da perna. Frequência: 73%",
                            SegmentoId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CriadoEm = new DateTime(2025, 6, 28, 18, 30, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Limites = "Terço médio/superior da perna - Da metade da perna até a fossa poplítea (abaixo do joelho). Frequência: 0%",
                            SegmentoId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CriadoEm = new DateTime(2025, 6, 28, 18, 30, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Limites = "Maleolar + Terço inferior - Úlcera extensa envolvendo tornozelo e porção inferior da perna. Frequência: 15%",
                            SegmentoId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CriadoEm = new DateTime(2025, 6, 28, 18, 30, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Limites = "Terço inferior + Terço médio/superior - Lesões ascendentes ou disseminadas, raras em úlceras puramente venosas. Frequência: 2%",
                            SegmentoId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Segmento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_segmentos");

                    b.ToTable("segmentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CriadoEm = new DateTime(2025, 6, 28, 18, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Ao redor dos maléolos (interno e externo), especialmente o maleolo medial (tíbia). Local mais comum de úlcera venosa. Associada à hipertensão venosa crônica.",
                            Nome = "Região maleolar ou perimaleolar"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CriadoEm = new DateTime(2025, 6, 28, 18, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Entre o maléolo e a metade da perna. Região de drenagem venosa crítica. Úlceras nesta zona indicam comprometimento venoso avançado.",
                            Nome = "Terço inferior da perna"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CriadoEm = new DateTime(2025, 6, 28, 18, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Da metade até abaixo do joelho. Menos comum para úlceras venosas. Úlceras aqui sugerem causas mistas (venosa + arterial ou vasculite).",
                            Nome = "Terço médio e superior da perna"
                        });
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Topografia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<int>("Lado")
                        .HasColumnType("integer")
                        .HasColumnName("lado");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("regiao_id");

                    b.Property<Guid>("UlceraId")
                        .HasColumnType("uuid")
                        .HasColumnName("ulcera_id");

                    b.HasKey("Id")
                        .HasName("pk_topografias");

                    b.HasIndex("RegiaoId")
                        .HasDatabaseName("ix_topografias_regiao_id");

                    b.HasIndex("UlceraId", "RegiaoId", "Lado")
                        .IsUnique();

                    b.ToTable("topografias", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Ulcera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.HasKey("Id")
                        .HasName("pk_ulceras");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_ulceras_paciente_id");

                    b.ToTable("ulceras", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.AvaliacaoUlcera", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Ulcera", "Ulcera")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UlceraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Cn2x.Iryo.UlceraVenosa.Domain.ValueObjects.Caracteristicas", "Caracteristicas", b1 =>
                        {
                            b1.Property<Guid>("AvaliacaoUlceraId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("BordasDefinidas")
                                .HasColumnType("boolean")
                                .HasColumnName("bordas_definidas");

                            b1.Property<bool>("Necrose")
                                .HasColumnType("boolean")
                                .HasColumnName("necrose");

                            b1.Property<bool>("OdorFetido")
                                .HasColumnType("boolean")
                                .HasColumnName("odor_fetido");

                            b1.Property<bool>("TecidoGranulacao")
                                .HasColumnType("boolean")
                                .HasColumnName("tecido_granulacao");

                            b1.HasKey("AvaliacaoUlceraId");

                            b1.ToTable("caracteristicas");

                            b1.WithOwner()
                                .HasForeignKey("AvaliacaoUlceraId");
                        });

                    b.OwnsOne("Cn2x.Iryo.UlceraVenosa.Domain.ValueObjects.Ceap", "ClassificacaoCeap", b1 =>
                        {
                            b1.Property<Guid>("AvaliacaoUlceraId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Anatomia")
                                .HasColumnType("integer")
                                .HasColumnName("anatomia");

                            b1.Property<int>("ClasseClinica")
                                .HasColumnType("integer")
                                .HasColumnName("classe_clinica");

                            b1.Property<int>("Etiologia")
                                .HasColumnType("integer")
                                .HasColumnName("etiologia");

                            b1.Property<int>("Patofisiologia")
                                .HasColumnType("integer")
                                .HasColumnName("patofisiologia");

                            b1.HasKey("AvaliacaoUlceraId");

                            b1.ToTable("ceap");

                            b1.WithOwner()
                                .HasForeignKey("AvaliacaoUlceraId");
                        });

                    b.OwnsOne("Cn2x.Iryo.UlceraVenosa.Domain.ValueObjects.SinaisInflamatorios", "SinaisInflamatorios", b1 =>
                        {
                            b1.Property<Guid>("AvaliacaoUlceraId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Calor")
                                .HasColumnType("boolean")
                                .HasColumnName("calor");

                            b1.Property<bool>("Dor")
                                .HasColumnType("boolean")
                                .HasColumnName("dor");

                            b1.Property<bool>("Edema")
                                .HasColumnType("boolean")
                                .HasColumnName("edema");

                            b1.Property<bool>("Eritema")
                                .HasColumnType("boolean")
                                .HasColumnName("eritema");

                            b1.Property<bool>("PerdadeFuncao")
                                .HasColumnType("boolean")
                                .HasColumnName("perda_de_funcao");

                            b1.Property<bool>("Rubor")
                                .HasColumnType("boolean")
                                .HasColumnName("rubor");

                            b1.HasKey("AvaliacaoUlceraId");

                            b1.ToTable("sinais_inflamatorios");

                            b1.WithOwner()
                                .HasForeignKey("AvaliacaoUlceraId");
                        });

                    b.Navigation("Caracteristicas")
                        .IsRequired();

                    b.Navigation("ClassificacaoCeap")
                        .IsRequired();

                    b.Navigation("SinaisInflamatorios")
                        .IsRequired();

                    b.Navigation("Ulcera");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.ExsudatoDaAvaliacao", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.AvaliacaoUlcera", "AvaliacaoUlcera")
                        .WithMany("Exsudatos")
                        .HasForeignKey("AvaliacaoUlceraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Exsudato", "Exsudato")
                        .WithMany()
                        .HasForeignKey("ExsudatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvaliacaoUlcera");

                    b.Navigation("Exsudato");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.ExsudatoDaUlcera", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Exsudato", "Exsudato")
                        .WithMany("ExsudatosDaUlcera")
                        .HasForeignKey("ExsudatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Ulcera", "Ulcera")
                        .WithMany()
                        .HasForeignKey("UlceraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exsudato");

                    b.Navigation("Ulcera");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.ImagemUlcera", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.AvaliacaoUlcera", null)
                        .WithMany("Imagens")
                        .HasForeignKey("UlceraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Ulcera", "Ulcera")
                        .WithMany()
                        .HasForeignKey("UlceraId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ulcera");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Medida", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.AvaliacaoUlcera", null)
                        .WithOne("Medida")
                        .HasForeignKey("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Medida", "UlceraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Ulcera", "Ulcera")
                        .WithOne()
                        .HasForeignKey("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Medida", "UlceraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ulcera");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.RegiaoAnatomica", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Segmento", "Segmento")
                        .WithMany("RegioesAnatomicas")
                        .HasForeignKey("SegmentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Segmento");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Topografia", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.RegiaoAnatomica", "Regiao")
                        .WithMany("Topografias")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Ulcera", "Ulcera")
                        .WithMany("Topografias")
                        .HasForeignKey("UlceraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");

                    b.Navigation("Ulcera");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Ulcera", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Ulceras")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.AvaliacaoUlcera", b =>
                {
                    b.Navigation("Exsudatos");

                    b.Navigation("Imagens");

                    b.Navigation("Medida");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Exsudato", b =>
                {
                    b.Navigation("ExsudatosDaUlcera");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Ulceras");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.RegiaoAnatomica", b =>
                {
                    b.Navigation("Topografias");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Segmento", b =>
                {
                    b.Navigation("RegioesAnatomicas");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Ulcera", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Topografias");
                });
#pragma warning restore 612, 618
        }
    }
}
