// <auto-generated />
using System;
using Cn2x.Iryo.UlceraVenosa.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cn2x.Iryo.UlceraVenosa.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.AvaliacaoUlcera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_avaliacao");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<int>("MesesDuracao")
                        .HasColumnType("integer")
                        .HasColumnName("meses_duracao");

                    b.Property<Guid>("UlceraId")
                        .HasColumnType("uuid")
                        .HasColumnName("ulcera_id");

                    b.HasKey("Id")
                        .HasName("pk_avaliacoes_ulcera");

                    b.HasIndex("UlceraId")
                        .HasDatabaseName("ix_avaliacoes_ulcera_ulcera_id");

                    b.ToTable("avaliacoes_ulcera", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Exsudato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_exsudato_tipos");

                    b.ToTable("exsudatos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Seroso - Transparente ou levemente amarelo, aquoso, fluido. Indicação: Fase inflamatória leve ou cicatrização. Conduta: Monitorar, manter hidratação da ferida."
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Serossanguinolento - Rosa claro, diluído com sangue, levemente viscoso. Indicação: Trauma leve ou início de granulação. Conduta: Avaliar trauma, proteger bordas."
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Sanguinolento - Vermelho vivo, líquido a viscoso. Indicação: Sangramento ativo ou lesão capilar. Conduta: Estancar, avaliar necessidade de sutura."
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Hemorrágico - Vermelho escuro ou vivo, espesso, com coágulos. Indicação: Hemorragia arterial ou venosa local. Conduta: Urgência médica, hemostasia."
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Purulento - Amarelo, esverdeado ou acastanhado, espesso, fétido. Indicação: Infecção bacteriana ativa. Conduta: Cultura, antibioticoterapia, limpeza."
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Fibrinoso - Esbranquiçado ou amarelado, gelatinoso, filamentoso. Indicação: Presença de fibrina, biofilme. Conduta: Desbridamento, controle da umidade."
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Catarral - Esbranquiçado e mucoide, viscoso. Indicação: Presente em áreas mucosas ou com inflamação leve. Conduta: Raro em úlceras venosas, observar."
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Necrótico - Marrom, cinza ou preto, espesso, seco ou úmido. Indicação: Presença de necrose tecidual. Conduta: Desbridamento enzimático ou cirúrgico."
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Putrilaginoso - Cinza-esverdeado, muito espesso, pegajoso, fétido. Indicação: Infecção crítica, tecido desvitalizado. Conduta: Ação rápida: desbridamento + antibiótico."
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CriadoEm = new DateTime(2025, 6, 28, 17, 32, 53, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Hiperexsudativo - Variável, muito abundante. Indicação: Descompensação venosa, linforreia, infecção. Conduta: Curativos superabsorventes, compressão."
                        });
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.ExsudatoDaAvaliacao", b =>
                {
                    b.Property<Guid>("AvaliacaoUlceraId")
                        .HasColumnType("uuid")
                        .HasColumnName("avaliacao_ulcera_id");

                    b.Property<Guid>("ExsudatoId")
                        .HasColumnType("uuid")
                        .HasColumnName("exsudato_id");

                    b.HasKey("AvaliacaoUlceraId", "ExsudatoId");

                    b.HasIndex("ExsudatoId")
                        .HasDatabaseName("ix_exsudatos_avaliacao_exsudato_id");

                    b.ToTable("exsudatos_avaliacao", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.ImagemAvaliacaoUlcera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("AvaliacaoUlceraId")
                        .HasColumnType("uuid")
                        .HasColumnName("avaliacao_ulcera_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.HasKey("Id")
                        .HasName("pk_imagem_avaliacao_ulcera");

                    b.HasIndex("AvaliacaoUlceraId")
                        .HasDatabaseName("ix_imagem_avaliacao_ulcera_avaliacao_ulcera_id");

                    b.ToTable("imagens_avaliacao_ulcera", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Lateralidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_lateralidades");

                    b.ToTable("lateralidades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-aaaa-bbbb-cccc-111111111111"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Nome = "Direita"
                        },
                        new
                        {
                            Id = new Guid("66666666-bbbb-cccc-dddd-222222222222"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Nome = "Esquerda"
                        });
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Medida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AvaliacaoUlceraId")
                        .HasColumnType("uuid")
                        .HasColumnName("avaliacao_ulcera_id");

                    b.Property<decimal?>("Comprimento")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("comprimento");

                    b.Property<decimal?>("Largura")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("largura");

                    b.Property<decimal?>("Profundidade")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("profundidade");

                    b.HasKey("Id")
                        .HasName("pk_medidas");

                    b.HasIndex("AvaliacaoUlceraId")
                        .IsUnique()
                        .HasDatabaseName("ix_medidas_avaliacao_ulcera_id");

                    b.ToTable("medidas", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_pacientes");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.RegiaoAnatomica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sigla");

                    b.HasKey("Id")
                        .HasName("pk_regiao_anatomica");

                    b.ToTable("regiao_anatomica", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Medial",
                            Sigla = "M"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Lateral",
                            Sigla = "L"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Anterior",
                            Sigla = "A"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Posterior",
                            Sigla = "P"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Anteromedial",
                            Sigla = "AM"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Posterolateral",
                            Sigla = "PL"
                        });
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.RegiaoTopograficaPe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sigla");

                    b.HasKey("Id")
                        .HasName("pk_regiao_topografica_pe");

                    b.ToTable("regiao_topografica_pe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Dorsal",
                            Sigla = "DOR"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Plantar",
                            Sigla = "PLA"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Calcâneo",
                            Sigla = "CAL"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Mediopé",
                            Sigla = "MED"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Antepé",
                            Sigla = "ANT"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Halux",
                            Sigla = "HAL"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Lateral",
                            Sigla = "LAT"
                        },
                        new
                        {
                            Id = new Guid("22222222-3333-4444-5555-666666666666"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Medial",
                            Sigla = "MEDL"
                        },
                        new
                        {
                            Id = new Guid("33333333-4444-5555-6666-777777777777"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Malelo Medial",
                            Sigla = "MMED"
                        },
                        new
                        {
                            Id = new Guid("44444444-5555-6666-7777-888888888888"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Malelo Lateral",
                            Sigla = "MLAT"
                        });
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Segmentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sigla");

                    b.HasKey("Id")
                        .HasName("pk_segmentacao");

                    b.ToTable("segmentacao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Da fossa poplítea até ~2/3 da altura da perna",
                            Sigla = "TS"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Da porção média até cerca de 1/3 acima do maléolo",
                            Sigla = "TM"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CriadoEm = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Desativada = false,
                            Descricao = "Do final do médio até os maléolos (região do tornozelo)",
                            Sigla = "TI"
                        });
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Topografia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<Guid>("LateralidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("lateralidade_id");

                    b.HasKey("Id")
                        .HasName("pk_topografias");

                    b.HasIndex("LateralidadeId")
                        .HasDatabaseName("ix_topografias_lateralidade_id");

                    b.ToTable("topografias", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Ulcera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Desativada")
                        .HasColumnType("boolean")
                        .HasColumnName("desativada");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid>("TopografiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("topografia_id");

                    b.HasKey("Id")
                        .HasName("pk_ulceras");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_ulceras_paciente_id");

                    b.HasIndex("TopografiaId")
                        .HasDatabaseName("ix_ulceras_topografia_id");

                    b.ToTable("ulceras", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.TopografiaPe", b =>
                {
                    b.HasBaseType("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Topografia");

                    b.Property<Guid>("RegiaoTopograficaPeId")
                        .HasColumnType("uuid")
                        .HasColumnName("regiao_topografica_pe_id");

                    b.HasIndex("RegiaoTopograficaPeId")
                        .HasDatabaseName("ix_topografias_regiao_topografica_pe_id");

                    b.ToTable("topografia_pe", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.TopografiaPerna", b =>
                {
                    b.HasBaseType("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Topografia");

                    b.Property<Guid>("RegiaoAnatomicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("regiao_anatomica_id");

                    b.Property<Guid>("SegmentacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("segmentacao_id");

                    b.HasIndex("RegiaoAnatomicaId")
                        .HasDatabaseName("ix_topografias_regiao_anatomica_id");

                    b.HasIndex("SegmentacaoId")
                        .HasDatabaseName("ix_topografias_segmentacao_id");

                    b.ToTable("topografia_perna", (string)null);
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.AvaliacaoUlcera", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Ulcera", "Ulcera")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UlceraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Cn2x.Iryo.UlceraVenosa.Domain.ValueObjects.Caracteristicas", "Caracteristicas", b1 =>
                        {
                            b1.Property<Guid>("avaliacao_ferida_id")
                                .HasColumnType("uuid");

                            b1.Property<bool>("BordasDefinidas")
                                .HasColumnType("boolean")
                                .HasColumnName("bordas_definidas");

                            b1.Property<bool>("Necrose")
                                .HasColumnType("boolean")
                                .HasColumnName("necrose");

                            b1.Property<bool>("OdorFetido")
                                .HasColumnType("boolean")
                                .HasColumnName("odor_fetido");

                            b1.Property<bool>("TecidoGranulacao")
                                .HasColumnType("boolean")
                                .HasColumnName("tecido_granulacao");

                            b1.HasKey("avaliacao_ferida_id");

                            b1.ToTable("caracteristicas");

                            b1.WithOwner()
                                .HasForeignKey("avaliacao_ferida_id");
                        });

                    b.OwnsOne("Cn2x.Iryo.UlceraVenosa.Domain.ValueObjects.SinaisInflamatorios", "SinaisInflamatorios", b1 =>
                        {
                            b1.Property<Guid>("avaliacao_ferida_id")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Calor")
                                .HasColumnType("boolean")
                                .HasColumnName("calor");

                            b1.Property<bool>("Dor")
                                .HasColumnType("boolean")
                                .HasColumnName("dor");

                            b1.Property<bool>("Edema")
                                .HasColumnType("boolean")
                                .HasColumnName("edema");

                            b1.Property<bool>("Eritema")
                                .HasColumnType("boolean")
                                .HasColumnName("eritema");

                            b1.Property<bool>("PerdadeFuncao")
                                .HasColumnType("boolean")
                                .HasColumnName("perda_de_funcao");

                            b1.Property<bool>("Rubor")
                                .HasColumnType("boolean")
                                .HasColumnName("rubor");

                            b1.HasKey("avaliacao_ferida_id");

                            b1.ToTable("sinais_inflamatorios");

                            b1.WithOwner()
                                .HasForeignKey("avaliacao_ferida_id");
                        });

                    b.Navigation("Caracteristicas")
                        .IsRequired();

                    b.Navigation("SinaisInflamatorios")
                        .IsRequired();

                    b.Navigation("Ulcera");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.ExsudatoDaAvaliacao", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.AvaliacaoUlcera", "AvaliacaoUlcera")
                        .WithMany("Exsudatos")
                        .HasForeignKey("AvaliacaoUlceraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Exsudato", "Exsudato")
                        .WithMany()
                        .HasForeignKey("ExsudatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvaliacaoUlcera");

                    b.Navigation("Exsudato");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.ImagemAvaliacaoUlcera", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.AvaliacaoUlcera", "AvaliacaoUlcera")
                        .WithMany("Imagens")
                        .HasForeignKey("AvaliacaoUlceraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Cn2x.Iryo.UlceraVenosa.Domain.ValueObjects.Imagem", "Imagem", b1 =>
                        {
                            b1.Property<Guid>("ImagemAvaliacaoUlceraId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("content_type");

                            b1.Property<DateTime>("DataCaptura")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("data_captura");

                            b1.Property<long>("TamanhoBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("tamanho_bytes");

                            b1.HasKey("ImagemAvaliacaoUlceraId");

                            b1.ToTable("imagem");

                            b1.WithOwner()
                                .HasForeignKey("ImagemAvaliacaoUlceraId");
                        });

                    b.Navigation("AvaliacaoUlcera");

                    b.Navigation("Imagem")
                        .IsRequired();
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Medida", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.AvaliacaoUlcera", "AvaliacaoUlcera")
                        .WithOne("Medida")
                        .HasForeignKey("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Medida", "AvaliacaoUlceraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvaliacaoUlcera");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Topografia", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Lateralidade", "Lateralidade")
                        .WithMany()
                        .HasForeignKey("LateralidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lateralidade");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Ulcera", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Ulceras")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Topografia", "Topografia")
                        .WithMany()
                        .HasForeignKey("TopografiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Cn2x.Iryo.UlceraVenosa.Domain.ValueObjects.Ceap", "Ceap", b1 =>
                        {
                            b1.Property<Guid>("ulcera_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Anatomia")
                                .HasColumnType("integer")
                                .HasColumnName("anatomia");

                            b1.Property<int>("ClasseClinica")
                                .HasColumnType("integer")
                                .HasColumnName("classe_clinica");

                            b1.Property<int>("Etiologia")
                                .HasColumnType("integer")
                                .HasColumnName("etiologia");

                            b1.Property<int>("Patofisiologia")
                                .HasColumnType("integer")
                                .HasColumnName("patofisiologia");

                            b1.HasKey("ulcera_id");

                            b1.ToTable("ceap", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ulcera_id");
                        });

                    b.Navigation("Ceap")
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Topografia");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.TopografiaPe", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Topografia", null)
                        .WithOne()
                        .HasForeignKey("Cn2x.Iryo.UlceraVenosa.Domain.Entities.TopografiaPe", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.RegiaoTopograficaPe", "RegiaoTopograficaPe")
                        .WithMany()
                        .HasForeignKey("RegiaoTopograficaPeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegiaoTopograficaPe");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.TopografiaPerna", b =>
                {
                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Topografia", null)
                        .WithOne()
                        .HasForeignKey("Cn2x.Iryo.UlceraVenosa.Domain.Entities.TopografiaPerna", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.RegiaoAnatomica", "RegiaoAnatomica")
                        .WithMany()
                        .HasForeignKey("RegiaoAnatomicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Segmentacao", "Segmentacao")
                        .WithMany()
                        .HasForeignKey("SegmentacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegiaoAnatomica");

                    b.Navigation("Segmentacao");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.AvaliacaoUlcera", b =>
                {
                    b.Navigation("Exsudatos");

                    b.Navigation("Imagens");

                    b.Navigation("Medida");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Ulceras");
                });

            modelBuilder.Entity("Cn2x.Iryo.UlceraVenosa.Domain.Entities.Ulcera", b =>
                {
                    b.Navigation("Avaliacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
